//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.11 at 01:28:27 PM CEST 
//


package megatravel.agentservice.soap;

import javax.xml.bind.annotation.XmlRegistry;

import megatravel.agentservice.model.AccommodationUnit;
import megatravel.agentservice.model.Location;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link DeleteAccommodationUnitRequest }
     * 
     */
    public DeleteAccommodationUnitRequest createDeleteAccommodationUnitRequest() {
        return new DeleteAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link LocationRequest }
     * 
     */
    public LocationRequest createLocationRequest() {
        return new LocationRequest();
    }

    /**
     * Create an instance of {@link AccommodationUnitResponse }
     * 
     */
    public AccommodationUnitResponse createAccommodationUnitResponse() {
        return new AccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link LocationResponse }
     * 
     */
    public LocationResponse createLocationResponse() {
        return new LocationResponse();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link AccommodationUnitRequest }
     * 
     */
    public AccommodationUnitRequest createAccommodationUnitRequest() {
        return new AccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link UpdateAccommodationUnitResponse }
     * 
     */
    public UpdateAccommodationUnitResponse createUpdateAccommodationUnitResponse() {
        return new UpdateAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link AddAccommodationUnitRequest }
     * 
     */
    public AddAccommodationUnitRequest createAddAccommodationUnitRequest() {
        return new AddAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link AddAccommodationUnitResponse }
     * 
     */
    public AddAccommodationUnitResponse createAddAccommodationUnitResponse() {
        return new AddAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link AccommodationUnitListResponse }
     * 
     */
    public AccommodationUnitListResponse createAccommodationUnitListResponse() {
        return new AccommodationUnitListResponse();
    }

    /**
     * Create an instance of {@link DeleteAccommodationUnitResponse }
     * 
     */
    public DeleteAccommodationUnitResponse createDeleteAccommodationUnitResponse() {
        return new DeleteAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link UpdateAccommodationUnitRequest }
     * 
     */
    public UpdateAccommodationUnitRequest createUpdateAccommodationUnitRequest() {
        return new UpdateAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link AccommodationUnitListRequest }
     * 
     */
    public AccommodationUnitListRequest createAccommodationUnitListRequest() {
        return new AccommodationUnitListRequest();
    }

}
